-- 1. Отменяем авто-права на будущее (REVOKE DEFAULT PRIVILEGES)
ALTER DEFAULT PRIVILEGES IN SCHEMA sales REVOKE ALL PRIVILEGES ON SEQUENCES FROM sales_manager;
ALTER DEFAULT PRIVILEGES IN SCHEMA sales REVOKE ALL PRIVILEGES ON TABLES FROM sales_manager;

ALTER DEFAULT PRIVILEGES IN SCHEMA catalog REVOKE SELECT ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog REVOKE SELECT ON TABLES FROM sales_manager;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog REVOKE ALL PRIVILEGES ON SEQUENCES FROM catalog_manager;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog REVOKE ALL PRIVILEGES ON TABLES FROM catalog_manager;

-- 2. Отзываем текущие права доступа в схеме sales
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA sales FROM sales_manager;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA sales FROM sales_manager;
REVOKE USAGE, CREATE ON SCHEMA sales FROM sales_manager;

-- 3. Отзываем текущие права доступа в схеме catalog
REVOKE SELECT ON ALL TABLES IN SCHEMA catalog FROM PUBLIC;
REVOKE USAGE ON SCHEMA catalog FROM PUBLIC;

REVOKE SELECT ON ALL TABLES IN SCHEMA catalog FROM sales_manager;
REVOKE USAGE ON SCHEMA catalog FROM sales_manager;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA catalog FROM catalog_manager;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA catalog FROM catalog_manager;
REVOKE USAGE, CREATE ON SCHEMA catalog FROM catalog_manager;
